version: '3'
services:

  azure-storage:
    image: azure-storage
    build: 
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4001:${AZURE_STORAGE_PORT}"
    env_file:
      - .env
    environment:
      - PORT=${AZURE_STORAGE_PORT}
      - STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${AZURE_STORAGE_ACCESS_KEY}
      - VIDEO_STORAGE_PORT=${AZURE_VIDEO_STORAGE_PORT}
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4002:${VIDEO_STREAMING_PORT}"
    env_file:
      - .env
    environment:
      - PORT=${VIDEO_STREAMING_PORT}
      - DBHOST=${VIDEO_STREAMING_DBHOST}
      - DBNAME=${VIDEO_STREAMING_DBNAME}
      - VIDEO_STORAGE_HOST=${VIDEO_STREAMING_STORAGE_HOST}
      - VIDEO_STORAGE_PORT=${VIDEO_STREAMING_STORAGE_PORT}
    restart: "no"