apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      serviceAccountName: acr-service-account
      imagePullSecrets:
        - name: acr-auth-secret
      containers:
        - name: video-streaming
          image: hrylog.azurecr.io/video-streaming:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Change this to 3000
          env:
            - name: PORT
              value: "3000" # Change this to 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming
spec:
  selector:
    app: video-streaming
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # Change this to 3000
      nodePort: 30001
